---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Confirm the role is disabled by default
      ansible.builtin.assert:
        that:
          - vm_enabled is false
