---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: List defined libvirt domains
      community.libvirt.virt:
        command: list_vms
      register: vm_remaining_domains
      failed_when: false
      changed_when: false

    - name: Assert VM is not defined
      ansible.builtin.assert:
        that:
          - vm_name not in (vm_remaining_domains.list_vms | default([]))
