---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Try and stop and remove Ollama
      community.docker.docker_container:
        name: "{{ ollama_container_name }}"
        state: absent
      register: result_ollama

    - name: Try and stop and remove Ollama WebUI
      community.docker.docker_container:
        name: "{{ ollama_webui_container_name }}"
        state: absent
      register: result_webui

    - name: Check Ollama containers are stopped
      ansible.builtin.assert:
        that:
          - not result_ollama.changed
          - not result_webui.changed
