---
- name: Get the list of services
  ansible.builtin.service_facts:

- name: Install and start Nomad
  block:
    - name: Remove legacy Hashicorp apt list
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/hashicorp.list
        state: absent

    - name: Remove legacy Hashicorp apt key
      ansible.builtin.file:
        path: /etc/apt/trusted.gpg.d/hashicorp.asc
        state: absent

    - name: Add Hashicorp apt repository
      ansible.builtin.deb822_repository:
        name: hashicorp
        types: deb
        uris: https://apt.releases.hashicorp.com
        suites: "{{ ansible_facts['lsb']['codename'] }}"
        components: main
        signed_by: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Install Nomad
      ansible.builtin.apt:
        name: nomad
        state: present
        update_cache: true

    - name: Template Nomad config
      ansible.builtin.template:
        src: nomad.hcl
        dest: /etc/nomad.d/nomad.hcl
      notify: restart nomad

    - name: Start Nomad
      ansible.builtin.systemd:
        name: "{{ nomad_service_name }}"
        state: started
        enabled: yes
  when: nomad_enabled is true

- name: Stop Nomad
  block:
    - name: Check if Nomad is installed
      ansible.builtin.stat:
        path: /usr/bin/nomad
      register: nomad_install

    - name: Stop and Uninstall Nomad
      block:
        - name: Stop Nomad
          ansible.builtin.systemd:
            name: "{{ nomad_service_name }}"
            state: stopped
            enabled: no
            daemon_reload: yes

        - name: Uninstall Nomad
          ansible.builtin.apt:
            name: nomad
            state: absent

      when: nomad_install.stat.exists
  when: nomad_enabled is false
