---
- ansible.builtin.import_tasks: grafana.yml
  when: stats_grafana_enabled | bool
- ansible.builtin.import_tasks: prometheus.yml
  when: stats_prometheus_enabled | bool
- ansible.builtin.import_tasks: telegraf.yml
  when: stats_telegraf_enabled | bool
- ansible.builtin.import_tasks: exporters.yml
  when: stats_exporters_enabled | bool
- ansible.builtin.import_tasks: influxdb.yml
  when: stats_influxdb_enabled | bool
- ansible.builtin.import_tasks: loki.yml
  when: stats_loki_enabled | bool
