---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Try and stop and remove Beszel Hub
      community.docker.docker_container:
        name: "{{ beszel_container_name }}"
        state: absent
      register: result_hub

    - name: Try and stop and remove Beszel Agent
      community.docker.docker_container:
        name: "{{ beszel_agent_container_name }}"
        state: absent
      register: result_agent

    - name: Check Beszel containers are stopped
      ansible.builtin.assert:
        that:
          - not result_hub.changed
          - not result_agent.changed
