permit_join: false
homeassistant: true
frontend: true
devices: devices.yaml

mqtt:
  base_topic: zigbee2mqtt
  user: "{{ mqtt_user }}"
  password: "{{ mqtt_password }}"
  client_id: "ZIGBEE2MQTT"
serial:
  port: "/dev/ttyACM0"
advanced:
  network_key:
    - 93
    - 193
    - 174
    - 2
    - 49
    - 79
    - 209
    - 80
    - 42
    - 146
    - 171
    - 177
    - 123
    - 39
    - 65
    - 36
  pan_id: 24716
  ext_pan_id:
    - 9
    - 46
    - 162
    - 83
    - 82
    - 209
    - 88
    - 52

availability:
    enabled: true
    active:
        # Time after which an active device will be marked as offline in minutes (default: 10 minutes)
        timeout: 10
        # Maximum jitter (in msec) allowed on timeout to avoid availability pings trying to trigger around the same time (default: 30000, min: 1000)
        max_jitter: 30000
        # Enable timeout backoff on failed availability pings (default: true)
        # Pattern used: x1.5, x3, x6, x12... (with default timeout of 10min: 10, 15, 30, 60, 120...)
        backoff: true
        # Pause availability pings when backoff reaches over this limit until a new Zigbee message is received from the device. (default: 0, min: 0)
        # A value of zero disables pausing, else see `backoff` pattern above.
        pause_on_backoff_gt: 0
    passive:
        # Time after which a passive device will be marked as offline in minutes (default: 1500 minutes aka 25 hours)
        timeout: 1500