---
apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://{{ ansible_facts['default_ipv4']['address'] }}:{{ loki_http_port }}
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "1"
