---
sonarr_enabled: false
sonarr_available_externally: false

# directories
sonarr_data_directory: "{{ docker_home }}/sonarr/config"
sonarr_movies_directory: "{{ movies_root }}"
sonarr_download_directory: "{{ downloads_root }}"

# uid / gid
sonarr_user_id: "{{ ansible_nas_system_uid }}"
sonarr_group_id: "{{ ansible_nas_system_gid }}"

# network
sonarr_port: "8989"
sonarr_hostname: "sonarr"

# docker
sonarr_container_name: "sonarr"
sonarr_image_name: "linuxserver/sonarr"
sonarr_image_version: "latest"

# specs
sonarr_memory: 1g

# Homepage widget (Settings > General in Sonarr UI)
sonarr_api_key: ""
