---
- name: Start Homeassistant
  block:
    - name: Create Home Assistant network
      community.docker.docker_network:
        name: "{{ homeassistant_network_name }}"

    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ homeassistant_directory }}"
        - "{{ homeassistant_directory }}/automations"
        - "{{ homeassistant_directory }}/templates"
        - "{{ homeassistant_directory }}/lovelace"
        - "{{ homeassistant_directory }}/www"
        - "{{ mosquitto_directory }}/config"
        - "{{ mosquitto_directory }}/data"
        - "{{ mosquitto_directory }}/log"
        - "{{ zigbee2mqtt_directory }}"
        - "{{ piper_directory }}"

    - name: Prepare config
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0640'
      loop:
        - src: zigbee2mqtt/configuration.yaml
          dest: "{{ zigbee2mqtt_directory }}"
        - src: mosquitto/users.conf
          dest: "{{ mosquitto_directory }}/config"
        - src: mosquitto/acl.conf
          dest: "{{ mosquitto_directory }}/config"
        - src: mosquitto/mosquitto.conf
          dest: "{{ mosquitto_directory }}/config"
        - src: homeassistant/configuration.yaml
          dest: "{{ homeassistant_directory }}"
      register: homeassistant_config

    - name: Check if user defined Home Assistant include files exist
      ansible.builtin.stat:
        path: "{{ inventory_dir }}/homeassistant/{{ item }}"
      loop:
        - scripts.yaml
        - scenes.yaml
        - climate.yaml
        - input_booleans.yaml
        - input_numbers.yaml
      register: homeassistant_include_files_src
      ignore_errors: true

    - name: Copy user defined Home Assistant include files
      ansible.builtin.copy:
        src: "{{ item.stat.path }}"
        dest: "{{ homeassistant_directory }}/"
        mode: '0640'
      loop: "{{ homeassistant_include_files_src.results | default([]) }}"
      when: item.stat is defined and item.stat.exists
      register: homeassistant_config_extra

    - name: Check if user defined Home Assistant automations directory exists
      ansible.builtin.stat:
        path: "{{ inventory_dir }}/homeassistant/automations"
      register: homeassistant_automations_src
      ignore_errors: true

    - name: Copy user defined Home Assistant automations
      ansible.builtin.copy:
        src: "{{ inventory_dir }}/homeassistant/automations/"
        dest: "{{ homeassistant_directory }}/automations/"
        mode: '0640'
        directory_mode: '0755'
      when: homeassistant_automations_src is not failed and homeassistant_automations_src.stat.isdir is defined and homeassistant_automations_src.stat.isdir
      register: homeassistant_config_automations

    - name: Check if user defined Home Assistant template directory exists
      ansible.builtin.stat:
        path: "{{ inventory_dir }}/homeassistant/templates"
      register: homeassistant_templates_src
      ignore_errors: true

    - name: Copy user defined Home Assistant template config
      ansible.builtin.copy:
        src: "{{ inventory_dir }}/homeassistant/templates/"
        dest: "{{ homeassistant_directory }}/templates/"
        mode: '0640'
        directory_mode: '0755'
      when: homeassistant_templates_src is not failed and homeassistant_templates_src.stat.isdir is defined and homeassistant_templates_src.stat.isdir
      register: homeassistant_config_templates

    - name: Check if user defined Home Assistant Lovelace directory exists
      ansible.builtin.stat:
        path: "{{ inventory_dir }}/homeassistant/lovelace"
      register: homeassistant_lovelace_src
      ignore_errors: true

    - name: Ensure default empty Lovelace dashboard registry exists
      ansible.builtin.copy:
        content: "{}\n"
        dest: "{{ homeassistant_directory }}/lovelace/dashboards.yaml"
        mode: '0640'
        force: false
      register: homeassistant_config_lovelace_default

    - name: Copy user defined Home Assistant Lovelace config
      ansible.builtin.copy:
        src: "{{ inventory_dir }}/homeassistant/lovelace/"
        dest: "{{ homeassistant_directory }}/lovelace/"
        mode: '0640'
        directory_mode: '0755'
      when: homeassistant_lovelace_src is not failed and homeassistant_lovelace_src.stat.isdir is defined and homeassistant_lovelace_src.stat.isdir
      register: homeassistant_config_lovelace

    - name: Check if user defined Home Assistant www directory exists
      ansible.builtin.stat:
        path: "{{ inventory_dir }}/homeassistant/www"
      register: homeassistant_www_src
      ignore_errors: true

    - name: Copy user defined Home Assistant www assets
      ansible.builtin.copy:
        src: "{{ inventory_dir }}/homeassistant/www/"
        dest: "{{ homeassistant_directory }}/www/"
        mode: '0644'
        directory_mode: '0755'
      when: homeassistant_www_src is not failed and homeassistant_www_src.stat.isdir is defined and homeassistant_www_src.stat.isdir
      register: homeassistant_config_www

    - name: Home Assistant Docker Container
      community.docker.docker_container:
        name: "{{ homeassistant_container_name }}"
        image: "{{ homeassistant_image_name }}:{{ homeassistant_image_version }}"
        pull: true
        volumes:
          - "{{ homeassistant_directory }}:/config:rw"
        network_mode: host
        restart_policy: unless-stopped
        restart: "{{ homeassistant_config is changed or (homeassistant_config_extra is defined and homeassistant_config_extra is changed) or (homeassistant_config_automations is defined and homeassistant_config_automations is changed) or (homeassistant_config_templates is defined and homeassistant_config_templates is changed) or (homeassistant_config_lovelace_default is defined and homeassistant_config_lovelace_default is changed) or (homeassistant_config_lovelace is defined and homeassistant_config_lovelace is changed) or (homeassistant_config_www is defined and homeassistant_config_www is changed) }}"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        labels:
          traefik.enable: "{{ homeassistant_available_externally | string }}"
          traefik.http.routers.homeassistant.rule: "Host(`{{ homeassistant_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.homeassistant.tls.certresolver: "letsencrypt"
          traefik.http.routers.homeassistant.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.homeassistant.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.homeassistant.loadbalancer.server.port: "{{ homeassistant_port }}"
          homepage.group: Home
          homepage.name: HomeAssistant
          homepage.icon: home-assistant
          homepage.href: "https://{{ homeassistant_hostname }}.{{ ansible_nas_domain }}"
          homepage.description: Home Automation
        memory: "{{ homeassistant_memory }}"

    - name: Mosquitto Docker Container
      community.docker.docker_container:
        name: "{{ mosquitto_container_name }}"
        image: "{{ mosquitto_image_name }}:{{ mosquitto_image_version }}"
        pull: true
        volumes:
          - "{{ mosquitto_directory }}/config:/mosquitto/config:rw"
          - "{{ mosquitto_directory }}/data:/mosquitto/data:rw"
          - "{{ mosquitto_directory }}/log:/mosquitto/log:rw"
        network_mode: "{{ homeassistant_network_name }}"
        ports:
          - "{{ mosquitto_port_a }}:1883"
          - "{{ mosquitto_port_b }}:9001"
        restart_policy: unless-stopped
        restart: "{{ homeassistant_config is changed }}"
        env:
          TZ: "{{ ansible_nas_timezone }}"
        memory: "{{ mosquitto_memory }}"
      when: (mosquitto_enabled | bool) or (homeassistant_zigbee_enabled | bool)

    - name: Zigbee2Mqtt Docker Container
      community.docker.docker_container:
        name: "{{ zigbee2mqtt_container_name }}"
        image: "{{ zigbee2mqtt_image_name }}:{{ zigbee2mqtt_image_version }}"
        pull: true
        volumes:
          - "/run/udev:/run/udev:ro"
          - "{{ zigbee2mqtt_directory }}:/app/data:rw"
        devices: "/dev/serial/by-id/{{ zigbee_dongle }}:/dev/ttyACM0"
        privileged: true
        network_mode: "{{ homeassistant_network_name }}"
        ports:
          - "{{ zigbee2mqtt_port }}:8080"
        restart_policy: unless-stopped
        restart: "{{ homeassistant_config is changed }}"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          ZIGBEE2MQTT_CONFIG_MQTT_SERVER : mqtt://{{ mosquitto_container_name }}
        labels:
          traefik.enable: "{{ homeassistant_available_externally | string }}"
          traefik.http.routers.zigbee2mqtt.rule: "Host(`{{ zigbee2mqtt_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.zigbee2mqtt.tls.certresolver: "letsencrypt"
          traefik.http.routers.zigbee2mqtt.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.zigbee2mqtt.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.zigbee2mqtt.loadbalancer.server.port: "8080"
          homepage.group: Home
          homepage.name: Zigbee2MQTT
          homepage.icon: zigbee2mqtt.png
          homepage.href: "https://{{ zigbee2mqtt_hostname }}.{{ ansible_nas_domain }}"
          homepage.description: Zigbee2MQTT broker
        memory: "{{ zigbee2mqtt_memory }}"
      when: homeassistant_zigbee_enabled | bool

    - name: Piper Docker Container
      community.docker.docker_container:
        name: "{{ piper_container_name }}"
        image: "{{ piper_image_name }}:{{ piper_image_version }}"
        pull: true
        command:
          - "--voice"
          - "{{ piper_voice }}"
        volumes:
          - "{{ piper_directory }}:/data:rw"
        network_mode: "{{ homeassistant_network_name }}"
        ports:
          - "{{ piper_port }}:10200"
        restart_policy: unless-stopped
        env:
          TZ: "{{ ansible_nas_timezone }}"
        memory: "{{ piper_memory }}"
      when: homeassistant_piper_enabled | bool

  when: homeassistant_enabled | bool


- name: Stop homeassistant
  block:
    - name: Stop homeassistant
      community.docker.docker_container:
        name: "{{ homeassistant_container_name }}"
        state: absent

    - name: Stop mosquitto
      community.docker.docker_container:
        name: "{{ mosquitto_container_name }}"
        state: absent

    - name: Stop zigbee2mqtt
      community.docker.docker_container:
        name: "{{ zigbee2mqtt_container_name }}"
        state: absent

    - name: Stop piper
      community.docker.docker_container:
        name: "{{ piper_container_name }}"
        state: absent

    - name: Delete Home Assistant network
      community.docker.docker_network:
        name: "{{ homeassistant_network_name }}"
        state: absent
  when: not (homeassistant_enabled | bool)

- name: Stop homeassistant zigbee2mqtt
  community.docker.docker_container:
    name: "{{ zigbee2mqtt_container_name }}"
    state: absent
  when: (homeassistant_enabled | bool) and not (homeassistant_zigbee_enabled | bool)

- name: Stop homeassistant mosquitto
  community.docker.docker_container:
    name: "{{ mosquitto_container_name }}"
    state: absent
  when: (homeassistant_enabled | bool) and not ((mosquitto_enabled | bool) or (homeassistant_zigbee_enabled | bool))

- name: Stop homeassistant piper
  community.docker.docker_container:
    name: "{{ piper_container_name }}"
    state: absent
  when: (homeassistant_enabled | bool) and not (homeassistant_piper_enabled | bool)
